theme: jekyll-theme-architect
name: TwbsHelper - Zend Framework module
tagline: Zend Framework module for easy integration of Twitter Bootstrap
owner: neilime
repository: neilime/zf-twbs-helper-module
exclude: ['nbproject']
markdown: kramdown
highlighter: rouge
baseurl: "/zf-twbs-helper-module"