theme: jekyll-theme-architect
name: TwbsHelper - Laminas ⚡ Bootstrap
tagline: Laminas (formerly Zend Framework) module for easy integration of Twitter Bootstrap
owner: neilime
repository: neilime/twbs-helper-module
exclude: ['nbproject']
markdown: kramdown
highlighter: rouge
baseurl: "/twbs-helper-module"
